### ISSUE TITLE
remove a book from the start screen

### ISSUE THREAD

**Issue by igalic** [robotlolita/raven#91]
i made the mistake of trying to find a book and open it's .json file
now i have two books listed on the start screen:

![raven start screen](https://cloud.githubusercontent.com/assets/497249/9059860/44855638-3aae-11e5-9d6f-59f948338cf2.png)

one of which looks like this:

![raven b0rkd book](https://cloud.githubusercontent.com/assets/497249/9059864/5208a3f0-3aae-11e5-9e97-7546650be4c2.png)

**Comment by igalic** [comment]
sorry for the noise._.

**Comment by igalic** [comment]
```
% cd ~/.Raven/
% rm -rf -- stuff-i-want-gone
```

sorry for the noise._.

**Comment by robotlolita** [comment]
No worries.

There isn't a way of removing things from the interface yet, it should be added eventually.
